on:
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

name: Standard

jobs:
  ci_test_sonar:
    name: CI - Sonar and Test
    if: ${{ success() && github.event_name != 'pull_request_target' && github.event_name != 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Name
        id: github_event_name
        run: echo '${{ github.event_name }}'
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'pull_request' }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn install
      # - run: npx prisma generate
      # - run: yarn run test:ci
      #
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ci_docker_dev:
    name: CI Docker - Dev
    needs: ci_test_sonar
    if: ${{ success() && github.event_name != 'pull_request_target' && github.event_name != 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Name
        id: github_event_name
        run: echo '${{ github.event_name }}'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: qzzdocker24/makima-backoffice:${{ github.sha}}, qzzdocker24/makima-backoffice:latest
  deploy:
    name: Deploy to K8S
    needs: ci_docker_dev
    if: ${{ success() && github.event_name != 'pull_request_target' && github.event_name != 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Event Name
        id: github_event_name
        run: echo '${{ github.event_name }}'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Set image tag 
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.makima-ms.image.tag = "${{ github.sha}}"' 'devops/helm/values.yaml'
      - name: Commit tag
        run: |
          git config --local user.email "biel_surf159@hotmail.com"
          git config --local user.name "GabSnow24"
          git commit -am "chore: change image tag to ${{ github.sha}}"
      - name: Update image version 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
          force: true

